export const GEORGIA_LAT_LNG = [32.9984, -83.6099];
export const MAP_ZOOM = 6;
export const FALL_MARKER_ID = 'fall-marker';
export const OCTOBER = 'october';
export const NOVEMBER = 'november';
export const COMPLETE = 'COMPLETE';
export const STARTING = 'STARTING';
export const FAILED = 'FAILED';
export const URL_MBGF = '/mbgf';